name: jaspr_svg
description: Svg for Jaspr -- From assets and from data URL
version: 0.1.0+2
repository: https://github.com/FlutterPlaza/jasprfire/tree/main/packages/jaspr_svg
homepage: https://www.flutterplaza.com/

environment:
  sdk: ^3.4.0

dependencies:
  jaspr: ^0.16.2
  universal_io: ^2.2.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
